### ISSUE TITLE
Docker compose up extied with code 1

### ISSUE THREAD

**Issue by ptesser** [Hopstok/u-drink-water-container#10]
Step:

1. Run `docker-compose up` inside the repository
2. This command response with `ERROR: Network u-drink-water_internal declared as external, but could not be found. Please create the network manually using `docker network create u-drink-water_internal` and try again.`
3. Run `docker network create u-drink-water_internal`
4. Run `docker-compose up` again
5. Starting to install volumes, during MySQL initialization exit with with code 1:

```
sql_1    | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
sql_1    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
sql_1    | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
sql_1    | Warning: Using a password on the command line interface can be insecure.
sql_1    | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
```

**Comment by Vannnu** [comment]
I don't get the problem probably some referred to .env file next week we'll see toghether

**Comment by ptesser** [comment]
Maybe the issue disappear after re run `docker-compose up`
